language: cpp
os: osx

before_install:
    - brew install igraph
      # - pyenv install 2.7.10
    - export PYTHON=3.5.0
    - brew outdated pyenv && brew upgrade pyenv
    - brew install pyenv-virtualenv
    - pyenv install ${PYTHON}
    - export PYENV_VERSION=$PYTHON
    - export PATH="/Users/travis/.pyenv/shims:${PATH}"
    - pyenv-virtualenv venv
    - source venv/bin/activate
    - python --version

script:
    - python -m pip install cmake twine
    - git clone https://github.com/Kuree/cgra_pnr
    - cd cgra_pnr
    - git checkout dev
    - git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel
