language: cpp
os: osx

before_install:
    - brew install igraph
    - export PYTHON=3.7.0
    - brew install pyenv-virtualenv
    - pyenv install ${PYTHON}
    - export PYENV_VERSION=$PYTHON
    - export PATH="/Users/travis/.pyenv/shims:${PATH}"
    - pyenv virtualenv venv
    - source /Users/travis/.pyenv/versions/${PYTHON}/envs/venv/bin/activate
    - python --version

script:
    - python -m pip install cmake twine wheel
    - git clone https://github.com/Kuree/cgra_pnr
    - cd cgra_pnr
    - git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel && cd ..
    - cd cyclone && python setup.py bdist_wheel && cd ..
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers =                             >> ~/.pypirc
    - echo "  pypi"                                    >> ~/.pypirc
    - echo                                             >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo repository=https://upload.pypi.org/legacy/  >> ~/.pypirc
    - echo username=keyi                               >> ~/.pypirc
    - echo password=$PYPI_PASSWORD                     >> ~/.pypirc
    - twine upload thunder/dist/*
    - twine upload cyclone/dist/*
