language: cpp
os: osx

before_install:
    - brew install igraph
    - brew install gcc@7
      # https://stackoverflow.com/q/49577343
      # apple strikes again!
    - pyenv install 2.7.10
    - pyenv install 3.5.0
    - pyenv versions

script:
    - pyenv local 3.5.0
    - pip install --user cmake
    - git clone https://github.com/Kuree/cgra_pnr
    - cd cgra_pnr && git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel
