language: cpp
os: osx

before_install:
    - brew install igraph
    - sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3";
    - brew install gcc@7
    - rm -rf '/usr/local/include/c++';
      # https://stackoverflow.com/q/49577343
      # apple strikes again!
    - which g++-7
    - pyenv install 2.7.10
    - pyenv install 3.5.0
    - pyenv versions

script:
    - pyenv local 3.5.0
    - pip install --user cmake
    - git clone https://github.com/Kuree/cgra_pnr
    - export CXX=g++-7
    - export CC=gcc-7
    - cd cgra_pnr && git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel
