language: cpp
os: osx

before_install:
    - brew install igraph
      # - pyenv install 2.7.10
    - pyenv install 3.5.0
    - pyenv versions

script:
    - pyenv local 3.5.0
    - pip install --user cmake
    - export VERBOSE=1
    - git clone https://github.com/Kuree/cgra_pnr
    - git checkout dev
    - cd cgra_pnr && git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel
