language: cpp
os: osx

before_install:
    - brew install cairo
    - brew install gmp
    - brew install igraph
    - brew link --overwrite igraph
      # - pyenv install 2.7.10
    - pyenv install 3.5.0
    - pyenv versions

script:
    - pyenv global 3.5.0
    - python -m pip install cmake twine
    - git clone https://github.com/Kuree/cgra_pnr
    - cd cgra_pnr
    - git checkout dev
    - git submodule update --init --recursive
    - cd thunder && python setup.py bdist_wheel
